done
craftyard/front-read pull request #58
Opened 2024-02-14 10:23 UTC by ThiagoRouge

2024-02-15 06:45 UTC, xHetso approved these changes

2024-02-15 08:50 UTC, NurGeo approved these changes

2024-02-15 08:50 UTC, NurGeo commented on src/model/services/get-workshop-models/service.test.ts
> +    expect(result.value).toEqual(ModelServiceFixtures.workshopModels);
1. на будущее, фикстуры и тесты ложи в один PR, чтобы можно было смотреть что же передается или возвращается.

2024-02-15 08:50 UTC, NurGeo commented on src/model/services/get-workshop-models/service.test.ts
> +  test('fail, user didnt log in', async () => {
этот тестовый случай не пишите, потому что вы не реализовали ее логику.

2024-02-15 08:50 UTC, NurGeo commented on src/model/services/get-workshop-models/service.test.ts
> +  test('fail, validation failed', async () => {
валидация, тоже не нужно. Этот тестовый случай делайте если написали какой то специальный валидатор.

2024-02-15 08:50 UTC, NurGeo commented on src/model/services/get-workshop-models/service.test.ts
не все тестовые случай предосмотрены. Подумай и добавь или обсуди с командой.

2024-02-15 08:51 UTC, NurGeo requested changes
упс, апрувнул, а не надо потому что не все тестовые случаи есть). Поэтому блокирую...

2024-02-29 10:44 UTC, merged

2024-02-29 10:44 UTC, FredSteady23 approved these changes